### PR TITLE
Add ability to create a plugin by template

### LINKED ISSUE #2: Plugin template
Create a command that generates a template for a new plugin.

it should be in the npm scripts as `create`
it should allow the user to choose the name of the plugin (preferably in the command `create prettier`)
it should allow choosing a language (currently) 
1. `typescript` which will also generate `tsconfig.json` and some starter files
2. `other` which will generate just a `package.json` in the relevant directory

you should checkout [cmd-ts](https://www.npmjs.com/package/cmd-ts) and [generate-template-files](https://www.npmjs.com/package/generate-template-files)

### PR DESCRIPTION
**Pull request by liorbentov**
Closes #2

### CODE REVIEW

**Comment by shamit6** [comment]
Thanks for your contribution.
I would appreciate if you could add:
1. description in the readme.
2. generate also `index.js` and `bin.js` files which are written in the generated `package.json`

**Comment by liorbentov** [comment]
@shamit6 - Do you mean that the template will also provide a README.MD file?
Regarding you second request, I think you should sync with @deanshub because he told me otherwise

**Comment by shamit6** [comment]
i mean to update the [How to create your own plugin](https://github.com/deanshub/nissix-plugins#how-to-create-your-own-plugin) section in the readme

**Comment by deanshub** [comment]
since a plugin can be in any language, @liorbentov and I agreed that the `bin` npm script should be an empty command or just an `echo bin` for `other` language
and the readme will be updated

**Comment by liorbentov** [comment]
@shamit6 , @deanshub - Please review again

**Pull request merged**
